name: lx_music_flutter
description: 落雪播放器Flutter版
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: 4.8.1
  json_serializable: 6.7.1
  package_info_plus: ^4.1.0
  device_info_plus: ^9.0.3
  easy_refresh: ^3.3.2+1
  fluttertoast: ^8.2.2
  just_audio: ^0.9.34
  audio_session: ^0.1.16
  rxdart: ^0.27.7
  sqflite: ^2.3.0
  dio: 5.3.2
  encrypt: ^5.0.1
  convert:
  shared_preferences: ^2.2.1
  extended_image: ^8.0.0
  get: 4.6.1
  webview_flutter: 4.4.2
  webview_flutter_android: ^3.12.0
  webview_flutter_wkwebview: ^3.9.0
  flutter_js:
#    git:
#      url: https://github.com/jonataslaw/getx.git
#      ref: 4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: 2.4.6

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/dist/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
